Extension { #name : #UndefinedObject }

{ #category : #'*Collections-Streams-Srfi41' }
UndefinedObject >> carParentSrfi41Stream: aSrfi41Stream [
	self shouldNotImplement
]

{ #category : #'*Collections-Streams-Srfi41' }
UndefinedObject >> cdrParentSrfi41Stream: aSrfi41Stream [
	self shouldNotImplement
]

{ #category : #'*Collections-Streams-Srfi41' }
UndefinedObject >> isEmptySrfi41Stream: aSrfi41Stream [
	^ true
]
